//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreKeepersWorkshop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ItemAmount {
            get {
                return ((int)(this["ItemAmount"]));
            }
            set {
                this["ItemAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110")]
        public int ItemID {
            get {
                return ((int)(this["ItemID"]));
            }
            set {
                this["ItemID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tab1_TabPage")]
        public string CurrentItemTab {
            get {
                return ((string)(this["CurrentItemTab"]));
            }
            set {
                this["CurrentItemTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ItemVariation {
            get {
                return ((int)(this["ItemVariation"]));
            }
            set {
                this["ItemVariation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InfoAmount {
            get {
                return ((int)(this["InfoAmount"]));
            }
            set {
                this["InfoAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InfoID {
            get {
                return ((int)(this["InfoID"]));
            }
            set {
                this["InfoID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InfoVariation {
            get {
                return ((int)(this["InfoVariation"]));
            }
            set {
                this["InfoVariation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Point MainFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainFormLocation"]));
            }
            set {
                this["MainFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Point ItemEditorLocation {
            get {
                return ((global::System.Drawing.Point)(this["ItemEditorLocation"]));
            }
            set {
                this["ItemEditorLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Point InventoryEditorLocation {
            get {
                return ((global::System.Drawing.Point)(this["InventoryEditorLocation"]));
            }
            set {
                this["InventoryEditorLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Point CookbookLocation {
            get {
                return ((global::System.Drawing.Point)(this["CookbookLocation"]));
            }
            set {
                this["CookbookLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InventoryBackground {
            get {
                return ((string)(this["InventoryBackground"]));
            }
            set {
                this["InventoryBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InventoryBackgroundCount {
            get {
                return ((int)(this["InventoryBackgroundCount"]));
            }
            set {
                this["InventoryBackgroundCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChatBackground {
            get {
                return ((string)(this["ChatBackground"]));
            }
            set {
                this["ChatBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ChatBackgroundCount {
            get {
                return ((int)(this["ChatBackgroundCount"]));
            }
            set {
                this["ChatBackgroundCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlayerBackground {
            get {
                return ((string)(this["PlayerBackground"]));
            }
            set {
                this["PlayerBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlayerBackgroundCount {
            get {
                return ((int)(this["PlayerBackgroundCount"]));
            }
            set {
                this["PlayerBackgroundCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WorldBackground {
            get {
                return ((string)(this["WorldBackground"]));
            }
            set {
                this["WorldBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WorldBackgroundCount {
            get {
                return ((int)(this["WorldBackgroundCount"]));
            }
            set {
                this["WorldBackgroundCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int DevToolDelay {
            get {
                return ((int)(this["DevToolDelay"]));
            }
            set {
                this["DevToolDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal RadialMoveScale {
            get {
                return ((decimal)(this["RadialMoveScale"]));
            }
            set {
                this["RadialMoveScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TopMost {
            get {
                return ((bool)(this["TopMost"]));
            }
            set {
                this["TopMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public decimal MapRenderingMax {
            get {
                return ((decimal)(this["MapRenderingMax"]));
            }
            set {
                this["MapRenderingMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal MapRenderingStart {
            get {
                return ((decimal)(this["MapRenderingStart"]));
            }
            set {
                this["MapRenderingStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal FishingCast {
            get {
                return ((decimal)(this["FishingCast"]));
            }
            set {
                this["FishingCast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal FishingPadding {
            get {
                return ((decimal)(this["FishingPadding"]));
            }
            set {
                this["FishingPadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Point ChunkViewerLocation {
            get {
                return ((global::System.Drawing.Point)(this["ChunkViewerLocation"]));
            }
            set {
                this["ChunkViewerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000000")]
        public string ChunkViewerAddress {
            get {
                return ((string)(this["ChunkViewerAddress"]));
            }
            set {
                this["ChunkViewerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChunkViewerDebug {
            get {
                return ((bool)(this["ChunkViewerDebug"]));
            }
            set {
                this["ChunkViewerDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("364")]
        public decimal ChunkViewerDebugScale {
            get {
                return ((decimal)(this["ChunkViewerDebugScale"]));
            }
            set {
                this["ChunkViewerDebugScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChunkViewerMobs {
            get {
                return ((bool)(this["ChunkViewerMobs"]));
            }
            set {
                this["ChunkViewerMobs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.2")]
        public float ChunkViewerScale {
            get {
                return ((float)(this["ChunkViewerScale"]));
            }
            set {
                this["ChunkViewerScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ProcessPriorityIndex {
            get {
                return ((int)(this["ProcessPriorityIndex"]));
            }
            set {
                this["ProcessPriorityIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int QuantitySelectButton1 {
            get {
                return ((int)(this["QuantitySelectButton1"]));
            }
            set {
                this["QuantitySelectButton1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int QuantitySelectButton2 {
            get {
                return ((int)(this["QuantitySelectButton2"]));
            }
            set {
                this["QuantitySelectButton2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int QuantitySelectButton3 {
            get {
                return ((int)(this["QuantitySelectButton3"]));
            }
            set {
                this["QuantitySelectButton3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int QuantitySelectButton4 {
            get {
                return ((int)(this["QuantitySelectButton4"]));
            }
            set {
                this["QuantitySelectButton4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999")]
        public int QuantitySelectButton5 {
            get {
                return ((int)(this["QuantitySelectButton5"]));
            }
            set {
                this["QuantitySelectButton5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ItemSkillset {
            get {
                return ((int)(this["ItemSkillset"]));
            }
            set {
                this["ItemSkillset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InfoSkillset {
            get {
                return ((int)(this["InfoSkillset"]));
            }
            set {
                this["InfoSkillset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Point TeleportAddressGuideLocation {
            get {
                return ((global::System.Drawing.Point)(this["TeleportAddressGuideLocation"]));
            }
            set {
                this["TeleportAddressGuideLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Point SkillEditorLocation {
            get {
                return ((global::System.Drawing.Point)(this["SkillEditorLocation"]));
            }
            set {
                this["SkillEditorLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SkillEditorUseEXP {
            get {
                return ((bool)(this["SkillEditorUseEXP"]));
            }
            set {
                this["SkillEditorUseEXP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Snow")]
        public global::System.Drawing.Color ConsoleForeColor {
            get {
                return ((global::System.Drawing.Color)(this["ConsoleForeColor"]));
            }
            set {
                this["ConsoleForeColor"] = value;
            }
        }
    }
}
